name: Build Package
on:
  push:
    paths:
      - "debian/**"
      - "hackberrypi-max17048.c"
      - "hackberrypicm5.dts"
      - ".github/actions/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:stable

    steps:
    - name: Fetch code
      uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y debhelper dkms dh-dkms devscripts build-essential

    - name: Build package
      run: |
        dpkg-buildpackage -us -uc -b
        mv ../*.deb ./hackberrypi-max17048-dkms-all.deb

    - name: Upload package
      uses: actions/upload-artifact@v7
      with:
        name: hackberrypi-max17048-dkms-all.deb
        path: hackberrypi-max17048-dkms-all.deb
    
    - name: Publish release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        files: |
          hackberrypi-max17048-dkms-all.deb
